##GCP Cloud Run
#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworldeclipse:latest', '-t', 'gcr.io/$PROJECT_ID/helloworldeclipse:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/helloworldeclipse:$BUILD_ID', '.']
#  id: 'build-image-helloworldeclipse'
#  waitFor: ['-']  # The '-' indicates that this step begins immediately.
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/$PROJECT_ID/helloworldeclipse:$COMMIT_SHA']
#  id: 'push-image-to-container-registry'
#  waitFor: ['build-image-helloworldeclipse']
#- name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - 'run'
#  - 'deploy'
#  - 'myhelloworldeclipseapp'
#  - '--image'
#  - 'gcr.io/$PROJECT_ID/helloworldeclipse:$COMMIT_SHA'
#  - '--region'
#  - 'us-east4'
#  - '--platform'
#  - 'managed'
#  - '--allow-unauthenticated'
#  waitFor: ['push-image-to-container-registry']
#  id: 'deploy-to-cloud-run'


steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworldeclipse:latest', '-t', 'gcr.io/$PROJECT_ID/helloworldeclipse:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/helloworldeclipse:$BUILD_ID', '.']
  id: 'build-image-helloworldeclipse'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/helloworldeclipse:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-helloworldeclipse']
#- name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - 'app'
#  - 'deploy'
#  waitFor: ['push-image-to-container-registry']
#  id: 'deploy-to-app-engine'
  

# steps for build the image in the krala-repo
#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/klara-repo/helloworldeclipse:$SHORT_SHA', '.']
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/klara-repo/helloworldeclipse:$SHORT_SHA']
#
#images:
#  - 'gcr.io/klara-repo/helloworldeclipse:$SHORT_SHA'
